2021-04-04 01:22: [38;5;196m
2021-04-04 01:22: Command userinfo raised the error: AttributeError: 'coroutine' object has no attribute 'cog'[0m
2021-04-04 01:22: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py:80: RuntimeWarning: coroutine 'General.user' was never awaited
2021-04-04 01:22:   self._context.run(self._callback, *self._args)
2021-04-04 01:22: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2021-04-04 01:23: [38;5;196m
2021-04-04 01:23: Command userinfo raised the error: AttributeError: 'NoneType' object has no attribute 'cog'[0m
2021-04-04 01:24: [38;5;196m
2021-04-04 01:24: Command userinfo raised the error: AttributeError: 'NoneType' object has no attribute 'cog'[0m
2021-04-04 18:49: [38;5;196m
2021-04-04 18:49: Command dumpemotes raised the error: TypeError: '<' not supported between instances of 'Emoji' and 'Emoji'[0m
2021-04-04 18:52: [38;5;196m
2021-04-04 18:52: Command dumpemotes raised the error: TypeError: '<' not supported between instances of 'Emoji' and 'Emoji'[0m
2021-04-04 22:00: [38;5;196m
2021-04-04 22:00: Command muterole raised the error: Forbidden: 403 Forbidden (error code: 50001): Missing Access[0m
2021-04-04 22:05: [38;5;196m
2021-04-04 22:05: Command muterole raised the error: Forbidden: 403 Forbidden (error code: 50001): Missing Access[0m
2021-04-04 22:07: [38;5;196m
2021-04-04 22:07: Command muterole raised the error: Forbidden: 403 Forbidden (error code: 50001): Missing Access[0m
2021-04-04 22:07: [38;5;196m
2021-04-04 22:07: Command muterole raised the error: Forbidden: 403 Forbidden (error code: 50001): Missing Access[0m
2021-04-04 22:08: [38;5;196m
2021-04-04 22:08: Command muterole raised the error: Forbidden: 403 Forbidden (error code: 50001): Missing Access[0m
